<?php

declare(strict_types=1);

namespace Lofmp\BlogGraphQl\Model\Resolver;

use Magento\Framework\GraphQl\Config\Element\Field;
use Magento\Framework\GraphQl\Query\ResolverInterface;
use Magento\Framework\GraphQl\Schema\Type\ResolveInfo;
use Lofmp\Blog\Helper\Data as blogHelper;

/**
 * Resolve Store Config information for SendFriend
 */
class BlogConfiguration implements ResolverInterface
{
    /**
     * @var blogHelper
     */
    private $blogHelper;
    /**
     * @param blogHelper $blogHelper
     */
    public function __construct(blogHelper $blogHelper)
    {
        $this->blogHelper = $blogHelper;
    }

    /**
     * @inheritDoc
     */
    public function resolve(Field $field, $context, ResolveInfo $info, array $value = null, array $args = null)
    {
        $store = $context->getExtensionAttributes()->getStore();
        $storeId = $store->getId();

        return [
            'general_settings_enable_rss'=> $this->blogHelper->getconfig('general_settings/enable_rss',$storeId),
            'general_settings_enable'=> $this->blogHelper->getconfig('general_settings/enable',$storeId),
            'general_settings_url_prefix'=> $this->blogHelper->getconfig('general_settings/url_prefix',$storeId),
            'general_settings_url_suffix'=> $this->blogHelper->getconfig('general_settings/url_suffix',$storeId),
            'general_settings_categories_urls'=> $this->blogHelper->getconfig('general_settings/categories_urls',$storeId),
            'general_settings_dateformat'=> $this->blogHelper->getconfig('general_settings/dateformat',$storeId),
            'general_settings_twitter_username'=> $this->blogHelper->getconfig('general_settings/twitter_username',$storeId),
            'general_settings_menu_title'=> $this->blogHelper->getconfig('general_settings/menu_title',$storeId),
            'general_settings_disable_comment'=> $this->blogHelper->getconfig('general_settings/disable_comment',$storeId),
            'general_settings_rssposts_show'=> $this->blogHelper->getconfig('general_settings/rssposts_show',$storeId),
            'general_settings_latestpagerss'=> $this->blogHelper->getconfig('general_settings/latestpagerss',$storeId),
            'general_settings_categoryrss'=> $this->blogHelper->getconfig('general_settings/categoryrss',$storeId),
            'general_settings_archiverss'=> $this->blogHelper->getconfig('general_settings/archiverss',$storeId),
            'general_settings_tagrss'=> $this->blogHelper->getconfig('general_settings/tagrss',$storeId),
            'general_settings_authorrss'=> $this->blogHelper->getconfig('general_settings/authorrss',$storeId),
            'general_settings_commentrss'=> $this->blogHelper->getconfig('general_settings/commentrss',$storeId),
            'general_settings_enable_networks'=> $this->blogHelper->getconfig('general_settings/enable_networks',$storeId),
            'general_settings_networks'=> $this->blogHelper->getconfig('general_settings/networks',$storeId),
            'general_settings_addthis_pubid'=> $this->blogHelper->getconfig('general_settings/addthis_pubid',$storeId),
            'blog_latest_page_exclued_categories'=> $this->blogHelper->getconfig('blog_latest_page/exclued_categories',$storeId),
            'blog_latest_page_page_title'=> $this->blogHelper->getconfig('blog_latest_page/page_title',$storeId),
            'blog_latest_page_meta_description'=> $this->blogHelper->getconfig('blog_latest_page/meta_description',$storeId),
            'blog_latest_page_meta_keywords'=> $this->blogHelper->getconfig('blog_latest_page/meta_keywords',$storeId),
            'blog_latest_page_posts_styles'=> $this->blogHelper->getconfig('blog_latest_page/posts_styles',$storeId),
            'blog_latest_page_maincontainer_selector'=> $this->blogHelper->getconfig('blog_latest_page/maincontainer_selector',$storeId),
            'category_page_show_breadcrumbs'=> $this->blogHelper->getconfig('category_page/show_breadcrumbs',$storeId),
            'category_page_show_toolbartop'=> $this->blogHelper->getconfig('category_page/show_toolbartop',$storeId),
            'category_page_show_toolbarbottom'=> $this->blogHelper->getconfig('category_page/show_toolbarbottom',$storeId),
            'category_page_show_image'=> $this->blogHelper->getconfig('category_page/show_image',$storeId),
            'category_page_image_width'=> $this->blogHelper->getconfig('category_page/image_width',$storeId),
            'category_page_image_height'=> $this->blogHelper->getconfig('category_page/image_height',$storeId),
            'category_page_show_title'=> $this->blogHelper->getconfig('category_page/show_title',$storeId),
            'category_page_show_shortdescription'=> $this->blogHelper->getconfig('category_page/show_shortdescription',$storeId),
            'category_page_shortdescription_count'=> $this->blogHelper->getconfig('category_page/shortdescription_count',$storeId),
            'category_page_show_readmorelink'=> $this->blogHelper->getconfig('category_page/show_readmorelink',$storeId),
            'category_page_show_categories'=> $this->blogHelper->getconfig('category_page/show_categories',$storeId),
            'category_page_show_author'=> $this->blogHelper->getconfig('category_page/show_author',$storeId),
            'category_page_show_commentcount'=> $this->blogHelper->getconfig('category_page/show_commentcount',$storeId),
            'category_page_show_updatedtime'=> $this->blogHelper->getconfig('category_page/show_updatedtime',$storeId),
            'category_page_show_createdtime'=> $this->blogHelper->getconfig('category_page/show_createdtime',$storeId),
            'category_page_show_hits'=> $this->blogHelper->getconfig('category_page/show_hits',$storeId),
            'category_page_show_tags'=> $this->blogHelper->getconfig('category_page/show_tags',$storeId),
            'post_page_show_likedisklike'=> $this->blogHelper->getconfig('post_page/show_likedisklike',$storeId),
            'post_page_show_image'=> $this->blogHelper->getconfig('post_page/show_image',$storeId),
            'post_page_image_width'=> $this->blogHelper->getconfig('post_page/image_width',$storeId),
            'post_page_image_height'=> $this->blogHelper->getconfig('post_page/image_height',$storeId),
            'post_page_show_title'=> $this->blogHelper->getconfig('post_page/show_title',$storeId),
            'post_page_show_description'=> $this->blogHelper->getconfig('post_page/show_description',$storeId),
            'post_page_show_categories'=> $this->blogHelper->getconfig('post_page/show_categories',$storeId),
            'post_page_show_author'=> $this->blogHelper->getconfig('post_page/show_author',$storeId),
            'post_page_show_commentcount'=> $this->blogHelper->getconfig('post_page/show_commentcount',$storeId),
            'post_page_show_updatedtime'=> $this->blogHelper->getconfig('post_page/show_updatedtime',$storeId),
            'post_page_show_createdtime'=> $this->blogHelper->getconfig('post_page/show_createdtime',$storeId),
            'post_page_show_socialblock'=> $this->blogHelper->getconfig('post_page/show_socialblock',$storeId),
            'post_page_show_hits'=> $this->blogHelper->getconfig('post_page/show_hits',$storeId),
            'post_page_show_tags'=> $this->blogHelper->getconfig('post_page/show_tags',$storeId),
            'post_page_show_socialnetwork'=> $this->blogHelper->getconfig('post_page/show_socialnetwork',$storeId),
            'post_page_enable_commentblock'=> $this->blogHelper->getconfig('post_page/enable_commentblock',$storeId),
            'post_page_allowable_tags'=> $this->blogHelper->getconfig('post_page/allowable_tags',$storeId),
            'post_page_comment_type'=> $this->blogHelper->getconfig('post_page/comment_type',$storeId),
            'post_page_auto_public'=> $this->blogHelper->getconfig('post_page/auto_public',$storeId),
            'post_page_numbercomment_perpage'=> $this->blogHelper->getconfig('post_page/numbercomment_perpage',$storeId),
            'post_page_limit_chars'=> $this->blogHelper->getconfig('post_page/limit_chars',$storeId),
            'post_page_enable_comment_reply'=> $this->blogHelper->getconfig('post_page/enable_comment_reply',$storeId),
            'post_page_show_captcha'=> $this->blogHelper->getconfig('post_page/show_captcha',$storeId),
            'post_page_captcha_publickey'=> $this->blogHelper->getconfig('post_page/captcha_publickey',$storeId),
            'post_page_captcha_privatekey'=> $this->blogHelper->getconfig('post_page/captcha_privatekey',$storeId),
            'post_page_enable_send_email'=> $this->blogHelper->getconfig('post_page/enable_send_email',$storeId),
            'post_page_recipient_email'=> $this->blogHelper->getconfig('post_page/recipient_email',$storeId),
            'post_page_sender_email_identity'=> $this->blogHelper->getconfig('post_page/sender_email_identity',$storeId),
            'post_page_email_template'=> $this->blogHelper->getconfig('post_page/email_template',$storeId),
            'post_page_enable_nextprev'=> $this->blogHelper->getconfig('post_page/enable_nextprev',$storeId),
            'post_page_enable_related'=> $this->blogHelper->getconfig('post_page/enable_related',$storeId),
            'post_page_related_carousel_layout'=> $this->blogHelper->getconfig('post_page/related_carousel_layout',$storeId),
            'post_page_mobile_items'=> $this->blogHelper->getconfig('post_page/mobile_items',$storeId),
            'post_page_tablet_small_items'=> $this->blogHelper->getconfig('post_page/tablet_small_items',$storeId),
            'post_page_tablet_items'=> $this->blogHelper->getconfig('post_page/tablet_items',$storeId),
            'post_page_portrait_items'=> $this->blogHelper->getconfig('post_page/portrait_items',$storeId),
            'post_page_default_items'=> $this->blogHelper->getconfig('post_page/default_items',$storeId),
            'post_page_large_items'=> $this->blogHelper->getconfig('post_page/large_items',$storeId),
            'post_page_autoplay'=> $this->blogHelper->getconfig('post_page/autoplay',$storeId),
            'post_page_autoplay_timeout'=> $this->blogHelper->getconfig('post_page/autoplay_timeout',$storeId),
            'post_page_dots'=> $this->blogHelper->getconfig('post_page/dots',$storeId),
            'post_page_nav'=> $this->blogHelper->getconfig('post_page/nav',$storeId),
            'post_page_nav_prev'=> $this->blogHelper->getconfig('post_page/nav_prev',$storeId),
            'post_page_nav_next'=> $this->blogHelper->getconfig('post_page/nav_next',$storeId),
            'post_page_enable_related_products'=> $this->blogHelper->getconfig('post_page/enable_related_products',$storeId),
            'post_page_related_products_carousel_layout'=> $this->blogHelper->getconfig('post_page/related_products_carousel_layout',$storeId),
            'post_page_mobile_items_products'=> $this->blogHelper->getconfig('post_page/mobile_items_products',$storeId),
            'post_page_tablet_small_items_products'=> $this->blogHelper->getconfig('post_page/tablet_small_items_products',$storeId),
            'post_page_tablet_items_products'=> $this->blogHelper->getconfig('post_page/tablet_items_products',$storeId),
            'post_page_portrait_items_products'=> $this->blogHelper->getconfig('post_page/portrait_items_products',$storeId),
            'post_page_default_items_products'=> $this->blogHelper->getconfig('post_page/default_items_products',$storeId),
            'post_page_large_items_products'=> $this->blogHelper->getconfig('post_page/large_items_products',$storeId),
            'post_page_autoplay_products'=> $this->blogHelper->getconfig('post_page/autoplay_products',$storeId),
            'post_page_autoplay_timeout_products'=> $this->blogHelper->getconfig('post_page/autoplay_timeout_products',$storeId),
            'post_page_dots_products'=> $this->blogHelper->getconfig('post_page/dots_products',$storeId),
            'post_page_nav_products'=> $this->blogHelper->getconfig('post_page/nav_products',$storeId),
            'post_page_nav_prev_products'=> $this->blogHelper->getconfig('post_page/nav_prev_products',$storeId),
            'post_page_nav_next_products'=> $this->blogHelper->getconfig('post_page/nav_next_products',$storeId),
            'product_page_enable_related_posts'=> $this->blogHelper->getconfig('product_page/enable_related_posts',$storeId),
            'product_page_show_image'=> $this->blogHelper->getconfig('product_page/show_image',$storeId),
            'product_page_image_width'=> $this->blogHelper->getconfig('product_page/image_width',$storeId),
            'product_page_image_height'=> $this->blogHelper->getconfig('product_page/image_height',$storeId),
            'product_page_show_title'=> $this->blogHelper->getconfig('product_page/show_title',$storeId),
            'product_page_show_shortdescription'=> $this->blogHelper->getconfig('product_page/show_shortdescription',$storeId),
            'product_page_show_categories'=> $this->blogHelper->getconfig('product_page/show_categories',$storeId),
            'product_page_show_author'=> $this->blogHelper->getconfig('product_page/show_author',$storeId),
            'product_page_show_commentcount'=> $this->blogHelper->getconfig('product_page/show_commentcount',$storeId),
            'product_page_show_updatedtime'=> $this->blogHelper->getconfig('product_page/show_updatedtime',$storeId),
            'product_page_show_createdtime'=> $this->blogHelper->getconfig('product_page/show_createdtime',$storeId),
            'product_page_show_hits'=> $this->blogHelper->getconfig('product_page/show_hits',$storeId),
            'product_page_show_tags'=> $this->blogHelper->getconfig('product_page/show_tags',$storeId),
            'product_page_show_socialnetwork'=> $this->blogHelper->getconfig('product_page/show_socialnetwork',$storeId),
            'product_page_item_height'=> $this->blogHelper->getconfig('product_page/item_height',$storeId),
            'product_page_number_item_percolumn'=> $this->blogHelper->getconfig('product_page/number_item_percolumn',$storeId),
            'product_page_large_max_items'=> $this->blogHelper->getconfig('product_page/large_max_items',$storeId),
            'product_page_large_items'=> $this->blogHelper->getconfig('product_page/large_items',$storeId),
            'product_page_portrait_items'=> $this->blogHelper->getconfig('product_page/portrait_items',$storeId),
            'product_page_tablet_items'=> $this->blogHelper->getconfig('product_page/tablet_items',$storeId),
            'product_page_tablet_small_items'=> $this->blogHelper->getconfig('product_page/tablet_small_items',$storeId),
            'product_page_mobile_items'=> $this->blogHelper->getconfig('product_page/mobile_items',$storeId),
            'product_page_autoplay_hoverpause'=> $this->blogHelper->getconfig('product_page/autoplay_hoverpause',$storeId),
            'product_page_autoplay'=> $this->blogHelper->getconfig('product_page/autoplay',$storeId),
            'product_page_loop'=> $this->blogHelper->getconfig('product_page/loop',$storeId),
            'product_page_dots'=> $this->blogHelper->getconfig('product_page/dots',$storeId),
            'product_page_nav'=> $this->blogHelper->getconfig('product_page/nav',$storeId),
            'product_page_nav_prev'=> $this->blogHelper->getconfig('product_page/nav_prev',$storeId),
            'product_page_nav_next'=> $this->blogHelper->getconfig('product_page/nav_next',$storeId),
            'sidebar_show_searchform'=> $this->blogHelper->getconfig('sidebar/show_searchform',$storeId),
            'sidebar_searchform_title'=> $this->blogHelper->getconfig('sidebar/searchform_title',$storeId),
            'sidebar_show_recentpostsblock'=> $this->blogHelper->getconfig('sidebar/show_recentpostsblock',$storeId),
            'sidebar_recentpostsblock_title'=> $this->blogHelper->getconfig('sidebar/recentpostsblock_title',$storeId),
            'sidebar_posts_per_page'=> $this->blogHelper->getconfig('sidebar/posts_per_page',$storeId),
            'sidebar_show_categoriesblock'=> $this->blogHelper->getconfig('sidebar/show_categoriesblock',$storeId),
            'sidebar_show_recentcommentsblock'=> $this->blogHelper->getconfig('sidebar/show_recentcommentsblock',$storeId),
            'sidebar_recentcommentsblock_title'=> $this->blogHelper->getconfig('sidebar/recentcommentsblock_title',$storeId),
            'sidebar_comments_per_page'=> $this->blogHelper->getconfig('sidebar/comments_per_page',$storeId),
            'sidebar_show_archiveblock'=> $this->blogHelper->getconfig('sidebar/show_archiveblock',$storeId),
            'sidebar_archiveblock_title'=> $this->blogHelper->getconfig('sidebar/archiveblock_title',$storeId),
            'sidebar_show_tagblock'=> $this->blogHelper->getconfig('sidebar/show_tagblock',$storeId),
            'sidebar_tagblock_title'=> $this->blogHelper->getconfig('sidebar/tagblock_title',$storeId),
            'sidebar_show_tagcountdown'=> $this->blogHelper->getconfig('sidebar/show_tagcountdown',$storeId),
            'sidebar_tag_cloud'=> $this->blogHelper->getconfig('sidebar/tag_cloud',$storeId),
            'sidebar_tags_per_page'=> $this->blogHelper->getconfig('sidebar/tags_per_page',$storeId),
            'blog_page_layout_type'=> $this->blogHelper->getconfig('blog_page/layout_type',$storeId),
            'blog_page_posts_styles'=> $this->blogHelper->getconfig('blog_page/posts_styles',$storeId),
            'blog_page_page_layout'=> $this->blogHelper->getconfig('blog_page/page_layout',$storeId),
            'blog_page_orderby'=> $this->blogHelper->getconfig('blog_page/orderby',$storeId),
            'blog_page_show_breadcrumbs'=> $this->blogHelper->getconfig('blog_page/show_breadcrumbs',$storeId),
            'blog_page_item_per_page'=> $this->blogHelper->getconfig('blog_page/item_per_page',$storeId),
            'blog_page_show_toolbartop'=> $this->blogHelper->getconfig('blog_page/show_toolbartop',$storeId),
            'blog_page_show_toolbarbottom'=> $this->blogHelper->getconfig('blog_page/show_toolbarbottom',$storeId),
            'blog_page_lg_column_item'=> $this->blogHelper->getconfig('blog_page/lg_column_item',$storeId),
            'blog_page_md_column_item'=> $this->blogHelper->getconfig('blog_page/md_column_item',$storeId),
            'blog_page_sm_column_item'=> $this->blogHelper->getconfig('blog_page/sm_column_item',$storeId),
            'blog_page_xs_column_item'=> $this->blogHelper->getconfig('blog_page/xs_column_item',$storeId),
            'blog_page_show_image'=> $this->blogHelper->getconfig('blog_page/show_image',$storeId),
            'blog_page_image_width'=> $this->blogHelper->getconfig('blog_page/image_width',$storeId),
            'blog_page_image_height'=> $this->blogHelper->getconfig('blog_page/image_height',$storeId),
            'blog_page_keep_ratio'=> $this->blogHelper->getconfig('blog_page/keep_ratio',$storeId),
            'blog_page_keep_frame'=> $this->blogHelper->getconfig('blog_page/keep_frame',$storeId),
            'blog_page_show_title'=> $this->blogHelper->getconfig('blog_page/show_title',$storeId),
            'blog_page_show_shortdescription'=> $this->blogHelper->getconfig('blog_page/show_shortdescription',$storeId),
            'blog_page_shortdescription_count'=> $this->blogHelper->getconfig('blog_page/shortdescription_count',$storeId),
            'blog_page_show_readmorelink'=> $this->blogHelper->getconfig('blog_page/show_readmorelink',$storeId),
            'blog_page_show_categories'=> $this->blogHelper->getconfig('blog_page/show_categories',$storeId),
            'blog_page_show_author'=> $this->blogHelper->getconfig('blog_page/show_author',$storeId),
            'blog_page_show_commentcount'=> $this->blogHelper->getconfig('blog_page/show_commentcount',$storeId),
            'blog_page_show_updatedtime'=> $this->blogHelper->getconfig('blog_page/show_updatedtime',$storeId),
            'blog_page_show_createdtime'=> $this->blogHelper->getconfig('blog_page/show_createdtime',$storeId),
            'blog_page_show_hits'=> $this->blogHelper->getconfig('blog_page/show_hits',$storeId),
            'blog_page_show_tags'=> $this->blogHelper->getconfig('blog_page/show_tags',$storeId),
            'blog_page_show_socialnetworks'=> $this->blogHelper->getconfig('blog_page/show_socialnetworks',$storeId),
            'ajaxscroll_selectors_enable_ajaxscroll'=> $this->blogHelper->getconfig('ajaxscroll_selectors/enable_ajaxscroll',$storeId),
            'ajaxscroll_selectors_enable_latest'=> $this->blogHelper->getconfig('ajaxscroll_selectors/enable_latest',$storeId),
            'ajaxscroll_selectors_enable_category'=> $this->blogHelper->getconfig('ajaxscroll_selectors/enable_category',$storeId),
            'ajaxscroll_selectors_enable_search'=> $this->blogHelper->getconfig('ajaxscroll_selectors/enable_search',$storeId),
            'ajaxscroll_selectors_enable_archive'=> $this->blogHelper->getconfig('ajaxscroll_selectors/enable_archive',$storeId),
            'ajaxscroll_selectors_enable_tag'=> $this->blogHelper->getconfig('ajaxscroll_selectors/enable_tag',$storeId),
            'ajaxscroll_selectors_enable_author'=> $this->blogHelper->getconfig('ajaxscroll_selectors/enable_author',$storeId),
            'ajaxscroll_selectors_enable_comment'=> $this->blogHelper->getconfig('ajaxscroll_selectors/enable_comment',$storeId),
            'ajaxscroll_selectors_content'=> $this->blogHelper->getconfig('ajaxscroll_selectors/content',$storeId),
            'ajaxscroll_selectors_pagination'=> $this->blogHelper->getconfig('ajaxscroll_selectors/pagination',$storeId),
            'ajaxscroll_selectors_toolbar'=> $this->blogHelper->getconfig('ajaxscroll_selectors/toolbar',$storeId),
            'ajaxscroll_selectors_next'=> $this->blogHelper->getconfig('ajaxscroll_selectors/next',$storeId),
            'ajaxscroll_selectors_grid_mode'=> $this->blogHelper->getconfig('ajaxscroll_selectors/grid_mode',$storeId),
            'ajaxscroll_selectors_loading_image'=> $this->blogHelper->getconfig('ajaxscroll_selectors/loading_image',$storeId),
            'ajaxscroll_selectors_loading_text'=> $this->blogHelper->getconfig('ajaxscroll_selectors/loading_text',$storeId),
            'ajaxscroll_selectors_done_text'=> $this->blogHelper->getconfig('ajaxscroll_selectors/done_text',$storeId),
            'ajaxscroll_selectors_hide_toolbar'=> $this->blogHelper->getconfig('ajaxscroll_selectors/hide_toolbar',$storeId),
            'ajaxscroll_selectors_local_mode'=> $this->blogHelper->getconfig('ajaxscroll_selectors/local_mode',$storeId),
            'ajaxscroll_selectors_buffer'=> $this->blogHelper->getconfig('ajaxscroll_selectors/buffer',$storeId),
            'ajaxscroll_selectors_load_more'=> $this->blogHelper->getconfig('ajaxscroll_selectors/load_more',$storeId),
            'ajaxscroll_selectors_load_more_text'=> $this->blogHelper->getconfig('ajaxscroll_selectors/load_more_text',$storeId),
            'other_settings_enable_authors_list'=> $this->blogHelper->getconfig('other_settings/enable_authors_list',$storeId),
            'other_settings_authors_url'=> $this->blogHelper->getconfig('other_settings/authors_url',$storeId),
            'other_settings_show_posts_count'=> $this->blogHelper->getconfig('other_settings/show_posts_count',$storeId),
            'other_settings_show_author_info'=> $this->blogHelper->getconfig('other_settings/show_author_info',$storeId),
            'other_settings_use_custom_post_link'=> $this->blogHelper->getconfig('other_settings/use_custom_post_link',$storeId),
            'other_settings_link_follow'=> $this->blogHelper->getconfig('other_settings/link_follow',$storeId),
            'other_settings_use_custom_post_img'=> $this->blogHelper->getconfig('other_settings/use_custom_post_img',$storeId),
            'importer_settings_enable_cron'=> $this->blogHelper->getconfig('importer_settings/enable_cron',$storeId),

        ];
    }
}
